version: "3.8"

services:
  # Backend Service
  backend-growth-dev:
    container_name: backend-growth-dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ai-testing.env
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "7000:7000"
    depends_on:
      - db-mongo-growth-dev
    networks:
      - server-network-growth-dev

  # MongoDB Service
  db-mongo-growth-dev:
    container_name: db-mongo-growth-dev
    image: mongo
    volumes:
      - mongo-data-growth-dev:/data/db
    restart: unless-stopped
    networks:
      - server-network-growth-dev

volumes:
  mongo-data-growth-dev:

networks:
  server-network-growth-dev:
    driver: bridge
